### ISSUE TITLE
Document how to connect Deadline Monitor to Render Queue

### ISSUE THREAD

**Issue by jusiskin** [aws/aws-rfdk#110]
Customers need to be able to connect the Deadline Monitor to the render farms that are deployed with RFDK, yet there is currently no documentation explaining this is done.

This was originally requested in https://github.com/aws/aws-rfdk/issues/105#issuecomment-683802301

---

This is a 📕 documentation issue

**Comment by koenverwimp** [comment]
Any news on this so I can further test the RFDK?

**Comment by ddneilson** [comment]
> 
> 
> Any news on this so I can further test the RFDK?

We do have a developer working on writing up some documentation on this, but I cannot provide an expected completion date. 

The jist of the documentation will be some information to help you set up a VPN connection to your deployed VPC -- https://aws.amazon.com/vpn/ -- then connect your Deadline Monitor to the Application Load Balancer endpoint that is created by the RenderQueue construct.

**Comment by ryyakobe** [comment]
We added a new section to our documentation on how to set up the connection to the render queue: https://docs.aws.amazon.com/rfdk/latest/guide/connecting-to-render-farm.html .

There is also a new optional step in the `Your first RFDK app` that demonstrates how to submit a rendering job with Deadline Client: https://docs.aws.amazon.com/rfdk/latest/guide/first-rfdk-app.html#_optional_submit_a_job_to_the_render_farm.

From the comment with the original request:

> I guess i need to create a PFX file from certificates that i can find in AWS secret manager? But i didnt get it to work so far. 

@koenverwimp please let us know if you still need help with the certificates, it might be that it wasn't working because the connection was not set up.

**Comment by koenverwimp** [comment]
Thanks for your reply. I got it to work in the meantime!
